require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe NewtestsController do

  # This should return the minimal set of attributes required to create a valid
  # Newtest. As you add validations to Newtest, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # NewtestsController. Be sure to keep this updated too.
  def valid_session
    {}
  end

  describe "GET index" do
    it "assigns all newtests as @newtests" do
      newtest = Newtest.create! valid_attributes
      get :index, {}, valid_session
      assigns(:newtests).should eq([newtest])
    end
  end

  describe "GET show" do
    it "assigns the requested newtest as @newtest" do
      newtest = Newtest.create! valid_attributes
      get :show, {:id => newtest.to_param}, valid_session
      assigns(:newtest).should eq(newtest)
    end
  end

  describe "GET new" do
    it "assigns a new newtest as @newtest" do
      get :new, {}, valid_session
      assigns(:newtest).should be_a_new(Newtest)
    end
  end

  describe "GET edit" do
    it "assigns the requested newtest as @newtest" do
      newtest = Newtest.create! valid_attributes
      get :edit, {:id => newtest.to_param}, valid_session
      assigns(:newtest).should eq(newtest)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new Newtest" do
        expect {
          post :create, {:newtest => valid_attributes}, valid_session
        }.to change(Newtest, :count).by(1)
      end

      it "assigns a newly created newtest as @newtest" do
        post :create, {:newtest => valid_attributes}, valid_session
        assigns(:newtest).should be_a(Newtest)
        assigns(:newtest).should be_persisted
      end

      it "redirects to the created newtest" do
        post :create, {:newtest => valid_attributes}, valid_session
        response.should redirect_to(Newtest.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved newtest as @newtest" do
        # Trigger the behavior that occurs when invalid params are submitted
        Newtest.any_instance.stub(:save).and_return(false)
        post :create, {:newtest => {}}, valid_session
        assigns(:newtest).should be_a_new(Newtest)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        Newtest.any_instance.stub(:save).and_return(false)
        post :create, {:newtest => {}}, valid_session
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested newtest" do
        newtest = Newtest.create! valid_attributes
        # Assuming there are no other newtests in the database, this
        # specifies that the Newtest created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        Newtest.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, {:id => newtest.to_param, :newtest => {'these' => 'params'}}, valid_session
      end

      it "assigns the requested newtest as @newtest" do
        newtest = Newtest.create! valid_attributes
        put :update, {:id => newtest.to_param, :newtest => valid_attributes}, valid_session
        assigns(:newtest).should eq(newtest)
      end

      it "redirects to the newtest" do
        newtest = Newtest.create! valid_attributes
        put :update, {:id => newtest.to_param, :newtest => valid_attributes}, valid_session
        response.should redirect_to(newtest)
      end
    end

    describe "with invalid params" do
      it "assigns the newtest as @newtest" do
        newtest = Newtest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Newtest.any_instance.stub(:save).and_return(false)
        put :update, {:id => newtest.to_param, :newtest => {}}, valid_session
        assigns(:newtest).should eq(newtest)
      end

      it "re-renders the 'edit' template" do
        newtest = Newtest.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        Newtest.any_instance.stub(:save).and_return(false)
        put :update, {:id => newtest.to_param, :newtest => {}}, valid_session
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested newtest" do
      newtest = Newtest.create! valid_attributes
      expect {
        delete :destroy, {:id => newtest.to_param}, valid_session
      }.to change(Newtest, :count).by(-1)
    end

    it "redirects to the newtests list" do
      newtest = Newtest.create! valid_attributes
      delete :destroy, {:id => newtest.to_param}, valid_session
      response.should redirect_to(newtests_url)
    end
  end

end
